FROM node:18

WORKDIR /app

COPY resources/ resources/
COPY src/ src/
COPY * .

RUN apt update > /dev/null
RUN apt install -y ffmpeg > /dev/null

RUN yarn global add node-gyp
RUN yarn install --frozen-lockfile

RUN yarn run build

RUN wget -nv https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
RUN chmod +x yt-dlp
RUN ./yt-dlp --version

EXPOSE 8675

ENV APP_DATA_VOLUME=/app/data
ENV META_URL_PREFIX=/app

CMD ./entrypoint.sh
