# Test and dry build project on master push and PR.

name: Test and dry build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Yarn test
        run: yarn run test

      - name: Yarn build
        run: |
          cp .env.example .env
          yarn run build
